version: '3.1'
services:
  userdemo:
    build: target/
    ports:
      - "8080:8080"


  PostgreSQL:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
      - POSTGRES_DB=docker
